# Generated by Django 6.0.4 on 2026-04-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSalao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('mensagem_boas_vindas', models.TextField(default='Olá! Bem-vindo(a) ao nosso salão. Como posso ajudar?')),
                ('mensagem_fora_horario', models.TextField(default='No momento estamos fora do horário de atendimento. Retornaremos em breve!')),
                ('horario_abertura', models.TimeField(default='08:00')),
                ('horario_fechamento', models.TimeField(default='19:00')),
                ('atendimento_sabado', models.BooleanField(default=True)),
                ('atendimento_domingo', models.BooleanField(default=False)),
                ('antecedencia_minima_horas', models.PositiveIntegerField(default=2, help_text='Horas mínimas de antecedência para agendamento')),
                ('antecedencia_lembrete_horas', models.PositiveIntegerField(default=24, help_text='Horas antes do agendamento para enviar lembrete')),
            ],
            options={
                'verbose_name': 'Configuração do Salão',
                'verbose_name_plural': 'Configurações do Salão',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cabelo', 'Cabelo'), ('unha', 'Unha'), ('sobrancelha', 'Sobrancelha'), ('outros', 'Outros')], max_length=20)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profissionais/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidades', models.ManyToManyField(related_name='profissionais', to='salao.especialidade')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='salao.especialidade')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['especialidade__tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='salao.profissional')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('profissional', 'dia_semana')},
            },
        ),
    ]
