# Generated by Django 6.0.4 on 2026-04-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True, help_text='Apresentação exibida no sistema e futuramente no site'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='portfolio/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='salao.profissional')),
            ],
            options={
                'verbose_name': 'Item de Portfólio',
                'verbose_name_plural': 'Portfólio',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
