# Generated by Django 6.0.4 on 2026-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0002_profissional_descricao_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True, default='', help_text='Apresentação exibida no sistema e futuramente no site'),
        ),
    ]
