# Generated by Django 6.0.4 on 2026-04-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lembrete', 'Lembrete'), ('confirmacao', 'Confirmação'), ('cancelamento', 'Cancelamento'), ('remarcacao', 'Remarcação')], max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('falha', 'Falha')], default='pendente', max_length=10)),
                ('agendada_para', models.DateTimeField()),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='agenda.agendamento')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['agendada_para'],
            },
        ),
    ]
