# Generated by Django 6.0.4 on 2026-04-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inicio', 'Início'), ('aguardando_servico', 'Aguardando escolha de serviço'), ('aguardando_profissional', 'Aguardando escolha de profissional'), ('aguardando_data', 'Aguardando data'), ('aguardando_horario', 'Aguardando horário'), ('aguardando_confirmacao', 'Aguardando confirmação'), ('orcamento', 'Montando orçamento'), ('livre', 'Conversa livre')], default='inicio', max_length=30)),
                ('dados_temp', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conversa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexto', to='whatsapp.conversa')),
            ],
            options={
                'verbose_name': 'Contexto de Conversa',
                'verbose_name_plural': 'Contextos de Conversa',
            },
        ),
    ]
